---
- name: Restart Web Application Container
  docker_container:
    name: my-webapp
    image: my-webapp-image
    state: started
    ports:
      - "5000:5000"
    recreate: yes
    pull: yes

# handlers file for webapp_role
